/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAuthMe200,
  GetAuthMe400,
  GetAuthMe401,
  GetAuthMe403,
  GetAuthMe404,
  GetAuthMe409,
  GetAuthMe429,
  GetAuthMe500,
  GetPosts200,
  GetPosts400,
  GetPosts401,
  GetPosts403,
  GetPosts404,
  GetPosts409,
  GetPosts429,
  GetPosts500,
  GetPostsParams,
  GetPostsPostId200,
  GetPostsPostId400,
  GetPostsPostId401,
  GetPostsPostId403,
  GetPostsPostId404,
  GetPostsPostId409,
  GetPostsPostId429,
  GetPostsPostId500,
  GetPostsPostIdFlat200,
  GetPostsPostIdFlat400,
  GetPostsPostIdFlat401,
  GetPostsPostIdFlat403,
  GetPostsPostIdFlat404,
  GetPostsPostIdFlat409,
  GetPostsPostIdFlat429,
  GetPostsPostIdFlat500,
  GetPostsPostIdTree200,
  GetPostsPostIdTree400,
  GetPostsPostIdTree401,
  GetPostsPostIdTree403,
  GetPostsPostIdTree404,
  GetPostsPostIdTree409,
  GetPostsPostIdTree429,
  GetPostsPostIdTree500,
  PostAuthLogin200,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin403,
  PostAuthLogin404,
  PostAuthLogin409,
  PostAuthLogin429,
  PostAuthLogin500,
  PostAuthLoginBody,
  PostAuthLogout200,
  PostAuthLogout400,
  PostAuthLogout401,
  PostAuthLogout403,
  PostAuthLogout404,
  PostAuthLogout409,
  PostAuthLogout429,
  PostAuthLogout500,
  PostAuthLogoutBody,
  PostAuthRegister201,
  PostAuthRegister400,
  PostAuthRegister401,
  PostAuthRegister403,
  PostAuthRegister404,
  PostAuthRegister409,
  PostAuthRegister429,
  PostAuthRegister500,
  PostAuthRegisterBody,
  PostPosts201,
  PostPosts400,
  PostPosts401,
  PostPosts403,
  PostPosts404,
  PostPosts409,
  PostPosts429,
  PostPosts500,
  PostPostsBody,
  PostPostsPostIdReply201,
  PostPostsPostIdReply400,
  PostPostsPostIdReply401,
  PostPostsPostIdReply403,
  PostPostsPostIdReply404,
  PostPostsPostIdReply409,
  PostPostsPostIdReply429,
  PostPostsPostIdReply500,
  PostPostsPostIdReplyBody
} from './models';

import { customInstance } from '../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register a new user
 */
export const postAuthRegister = (
    postAuthRegisterBody: PostAuthRegisterBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthRegister201>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthRegisterBody, signal
    },
      options);
    }
  


export const getPostAuthRegisterMutationOptions = <TError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister429 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: PostAuthRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = PostAuthRegisterBody
    export type PostAuthRegisterMutationError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister429 | PostAuthRegister500

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister429 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: PostAuthRegisterBody},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Login with username and password
 */
export const postAuthLogin = (
    postAuthLoginBody: PostAuthLoginBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthLogin200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthLoginBody, signal
    },
      options);
    }
  


export const getPostAuthLoginMutationOptions = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin429 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: PostAuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = PostAuthLoginBody
    export type PostAuthLoginMutationError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin429 | PostAuthLogin500

    /**
 * @summary Login with username and password
 */
export const usePostAuthLogin = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin429 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: PostAuthLoginBody},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get current authenticated user information
 */
export const getAuthMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAuthMe200>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) => getAuthMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>
export type GetAuthMeQueryError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500


export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current authenticated user information
 */

export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe429 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logout and revoke refresh token
 */
export const postAuthLogout = (
    postAuthLogoutBody: PostAuthLogoutBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthLogout200>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthLogoutBody, signal
    },
      options);
    }
  


export const getPostAuthLogoutMutationOptions = <TError = PostAuthLogout400 | PostAuthLogout401 | PostAuthLogout403 | PostAuthLogout404 | PostAuthLogout409 | PostAuthLogout429 | PostAuthLogout500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, {data: PostAuthLogoutBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    export type PostAuthLogoutMutationBody = PostAuthLogoutBody
    export type PostAuthLogoutMutationError = PostAuthLogout400 | PostAuthLogout401 | PostAuthLogout403 | PostAuthLogout404 | PostAuthLogout409 | PostAuthLogout429 | PostAuthLogout500

    /**
 * @summary Logout and revoke refresh token
 */
export const usePostAuthLogout = <TError = PostAuthLogout400 | PostAuthLogout401 | PostAuthLogout403 | PostAuthLogout404 | PostAuthLogout409 | PostAuthLogout429 | PostAuthLogout500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        {data: PostAuthLogoutBody},
        TContext
      > => {

      const mutationOptions = getPostAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get all posts with pagination
 */
export const getPosts = (
    params?: GetPostsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPosts200>(
      {url: `/posts`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetPostsQueryKey = (params?: GetPostsParams,) => {
    return [
    `/posts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPostsQueryOptions = <TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500>(params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) => getPosts(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>
export type GetPostsQueryError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500


export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500>(
 params: undefined |  GetPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all posts with pagination
 */

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = GetPosts400 | GetPosts401 | GetPosts403 | GetPosts404 | GetPosts409 | GetPosts429 | GetPosts500>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new post with an initial number
 */
export const postPosts = (
    postPostsBody: PostPostsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostPosts201>(
      {url: `/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPostsBody, signal
    },
      options);
    }
  


export const getPostPostsMutationOptions = <TError = PostPosts400 | PostPosts401 | PostPosts403 | PostPosts404 | PostPosts409 | PostPosts429 | PostPosts500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBody}, TContext> => {

const mutationKey = ['postPosts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPosts>>, {data: PostPostsBody}> = (props) => {
          const {data} = props ?? {};

          return  postPosts(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPostsMutationResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>
    export type PostPostsMutationBody = PostPostsBody
    export type PostPostsMutationError = PostPosts400 | PostPosts401 | PostPosts403 | PostPosts404 | PostPosts409 | PostPosts429 | PostPosts500

    /**
 * @summary Create a new post with an initial number
 */
export const usePostPosts = <TError = PostPosts400 | PostPosts401 | PostPosts403 | PostPosts404 | PostPosts409 | PostPosts429 | PostPosts500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPosts>>,
        TError,
        {data: PostPostsBody},
        TContext
      > => {

      const mutationOptions = getPostPostsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get a single post by ID
 */
export const getPostsPostId = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPostsPostId200>(
      {url: `/posts/${postId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPostsPostIdQueryKey = (postId?: string,) => {
    return [
    `/posts/${postId}`
    ] as const;
    }

    
export const getGetPostsPostIdQueryOptions = <TData = Awaited<ReturnType<typeof getPostsPostId>>, TError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsPostIdQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostId>>> = ({ signal }) => getPostsPostId(postId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsPostId>>>
export type GetPostsPostIdQueryError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500


export function useGetPostsPostId<TData = Awaited<ReturnType<typeof getPostsPostId>>, TError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostId<TData = Awaited<ReturnType<typeof getPostsPostId>>, TError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostId<TData = Awaited<ReturnType<typeof getPostsPostId>>, TError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single post by ID
 */

export function useGetPostsPostId<TData = Awaited<ReturnType<typeof getPostsPostId>>, TError = GetPostsPostId400 | GetPostsPostId401 | GetPostsPostId403 | GetPostsPostId404 | GetPostsPostId409 | GetPostsPostId429 | GetPostsPostId500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsPostIdQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Reply to a post or node with an operation
 */
export const postPostsPostIdReply = (
    postId: string,
    postPostsPostIdReplyBody: PostPostsPostIdReplyBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostPostsPostIdReply201>(
      {url: `/posts/${postId}/reply`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPostsPostIdReplyBody, signal
    },
      options);
    }
  


export const getPostPostsPostIdReplyMutationOptions = <TError = PostPostsPostIdReply400 | PostPostsPostIdReply401 | PostPostsPostIdReply403 | PostPostsPostIdReply404 | PostPostsPostIdReply409 | PostPostsPostIdReply429 | PostPostsPostIdReply500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPostsPostIdReply>>, TError,{postId: string;data: PostPostsPostIdReplyBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postPostsPostIdReply>>, TError,{postId: string;data: PostPostsPostIdReplyBody}, TContext> => {

const mutationKey = ['postPostsPostIdReply'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPostsPostIdReply>>, {postId: string;data: PostPostsPostIdReplyBody}> = (props) => {
          const {postId,data} = props ?? {};

          return  postPostsPostIdReply(postId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPostsPostIdReplyMutationResult = NonNullable<Awaited<ReturnType<typeof postPostsPostIdReply>>>
    export type PostPostsPostIdReplyMutationBody = PostPostsPostIdReplyBody
    export type PostPostsPostIdReplyMutationError = PostPostsPostIdReply400 | PostPostsPostIdReply401 | PostPostsPostIdReply403 | PostPostsPostIdReply404 | PostPostsPostIdReply409 | PostPostsPostIdReply429 | PostPostsPostIdReply500

    /**
 * @summary Reply to a post or node with an operation
 */
export const usePostPostsPostIdReply = <TError = PostPostsPostIdReply400 | PostPostsPostIdReply401 | PostPostsPostIdReply403 | PostPostsPostIdReply404 | PostPostsPostIdReply409 | PostPostsPostIdReply429 | PostPostsPostIdReply500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPostsPostIdReply>>, TError,{postId: string;data: PostPostsPostIdReplyBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPostsPostIdReply>>,
        TError,
        {postId: string;data: PostPostsPostIdReplyBody},
        TContext
      > => {

      const mutationOptions = getPostPostsPostIdReplyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get the nested tree structure of a post
 */
export const getPostsPostIdTree = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPostsPostIdTree200>(
      {url: `/posts/${postId}/tree`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPostsPostIdTreeQueryKey = (postId?: string,) => {
    return [
    `/posts/${postId}/tree`
    ] as const;
    }

    
export const getGetPostsPostIdTreeQueryOptions = <TData = Awaited<ReturnType<typeof getPostsPostIdTree>>, TError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsPostIdTreeQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostIdTree>>> = ({ signal }) => getPostsPostIdTree(postId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsPostIdTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsPostIdTree>>>
export type GetPostsPostIdTreeQueryError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500


export function useGetPostsPostIdTree<TData = Awaited<ReturnType<typeof getPostsPostIdTree>>, TError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdTree>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostIdTree<TData = Awaited<ReturnType<typeof getPostsPostIdTree>>, TError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdTree>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostIdTree<TData = Awaited<ReturnType<typeof getPostsPostIdTree>>, TError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the nested tree structure of a post
 */

export function useGetPostsPostIdTree<TData = Awaited<ReturnType<typeof getPostsPostIdTree>>, TError = GetPostsPostIdTree400 | GetPostsPostIdTree401 | GetPostsPostIdTree403 | GetPostsPostIdTree404 | GetPostsPostIdTree409 | GetPostsPostIdTree429 | GetPostsPostIdTree500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsPostIdTreeQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a flat list of all nodes in a post sorted by creation date
 */
export const getPostsPostIdFlat = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPostsPostIdFlat200>(
      {url: `/posts/${postId}/flat`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPostsPostIdFlatQueryKey = (postId?: string,) => {
    return [
    `/posts/${postId}/flat`
    ] as const;
    }

    
export const getGetPostsPostIdFlatQueryOptions = <TData = Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsPostIdFlatQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostIdFlat>>> = ({ signal }) => getPostsPostIdFlat(postId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsPostIdFlatQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsPostIdFlat>>>
export type GetPostsPostIdFlatQueryError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500


export function useGetPostsPostIdFlat<TData = Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdFlat>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdFlat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostIdFlat<TData = Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdFlat>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdFlat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsPostIdFlat<TData = Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a flat list of all nodes in a post sorted by creation date
 */

export function useGetPostsPostIdFlat<TData = Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError = GetPostsPostIdFlat400 | GetPostsPostIdFlat401 | GetPostsPostIdFlat403 | GetPostsPostIdFlat404 | GetPostsPostIdFlat409 | GetPostsPostIdFlat429 | GetPostsPostIdFlat500>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdFlat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsPostIdFlatQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




