/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetPosts200DataPostsItem } from './getPosts200DataPostsItem';
import type { GetPosts200DataPagination } from './getPosts200DataPagination';

export type GetPosts200Data = {
  posts: GetPosts200DataPostsItem[];
  pagination: GetPosts200DataPagination;
};
