/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type GetPostsPostId200Data = {
  id: number;
  user_id: number;
  username: string;
  initial_number: number;
  nodes_count: number;
  created_at: string;
};
