/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetPosts400ErrorsItem } from './getPosts400ErrorsItem';

export type GetPosts400 = {
  success: boolean;
  message: string;
  statusCode: number;
  errors?: GetPosts400ErrorsItem[];
};
