/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetPostsPostIdFlat200DataItem } from './getPostsPostIdFlat200DataItem';

export type GetPostsPostIdFlat200 = {
  success: boolean;
  message: string;
  data: GetPostsPostIdFlat200DataItem[];
  statusCode: number;
};
