/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type GetPostsPostIdFlat200DataItem = {
  id: number;
  post_id: number;
  /** @nullable */
  parent_id: number | null;
  user_id: number;
  username: string;
  /** @nullable */
  operation: string | null;
  /** @nullable */
  operand_value: number | null;
  result_value: number;
  depth: number;
  created_at: string;
};
