/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetPostsPostIdTree200Data } from './getPostsPostIdTree200Data';

export type GetPostsPostIdTree200 = {
  success: boolean;
  message: string;
  data: GetPostsPostIdTree200Data;
  statusCode: number;
};
