/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type GetPostsPostIdTree200Data = {
  id: number;
  value: number;
  /** @nullable */
  operation: string | null;
  /** @nullable */
  operand: string | null;
  user_id: number;
  username: string;
  created_at: string;
  children: unknown[];
};
