/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type PostPostsPostIdReplyBodyOperation = typeof PostPostsPostIdReplyBodyOperation[keyof typeof PostPostsPostIdReplyBodyOperation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPostsPostIdReplyBodyOperation = {
  '+': '+',
  '-': '-',
  '*': '*',
  '/': '/',
  '^': '^',
} as const;
