/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostAuthLogout400ErrorsItem } from './postAuthLogout400ErrorsItem';

export type PostAuthLogout400 = {
  success: boolean;
  message: string;
  statusCode: number;
  errors?: PostAuthLogout400ErrorsItem[];
};
