/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type PostAuthLogout200 = {
  success: boolean;
  message: string;
  /** @nullable */
  data: string | null;
  statusCode: number;
};
