/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostPosts201Data } from './postPosts201Data';

export type PostPosts201 = {
  success: boolean;
  message: string;
  data: PostPosts201Data;
  statusCode: number;
};
