/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ellty Second Test API
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostPostsPostIdReplyBodyOperation } from './postPostsPostIdReplyBodyOperation';

export type PostPostsPostIdReplyBody = {
  /** @nullable */
  parentId: number | null;
  operation: PostPostsPostIdReplyBodyOperation;
  operandValue: number;
};
